### ISSUE TITLE
Update automatico Conferenze 

### ISSUE THREAD

**Issue by waltermaffy** [ventunobtc/ventuno-space#23]
Per ogni conferenza nella pagina andrebbero spostate in una nuova sezione "Conferenze Passate" le conferenze che hanno una data < today

**Comment by GitGab19** [comment]
Sto creando una sezione aggiuntiva per le conferenze passate, e un'ulteriore sezione per quelle in corso!
Ho aggiunto dei campi nel body della singola conferenza, per formattare meglio la data di inizio e fine di ognuna di esse.
Credo di aver quasi finito in locale, posso creare un branch e fare un PR a breve
