### ISSUE TITLE
Proposal: aggiungere nuova pagina "Bitcoin physical Store"

### ISSUE THREAD

**Issue by villaggiobtc** [ventunobtc/ventuno-space#28]
Tra le risorse Bitcoin, si potrebbe aggiungere anche la nuova pagina:

"BITCOIN PHYSICAL STORE".
Punti fisici e negozi sul territorio per consulenze, formazione, educazione, vendita di gadget bitcoin ed incontri in presenza per persone e imprese che si vogliono avvicinare al mondo Bitcoin:
   -  [VILLAGGIO BITCOIN](https://goo.gl/maps/64A9gsJ68WHo97Yk6) - Via Roma, 37, 25047 - Darfo Boario Terme (Brescia)
   -  [COMPROEURO](https://g.page/comproeuro-Rovereto?share) - Via Rialto, 16, 38068 - Rovereto (Trento)

**Comment by waltermaffy** [comment]
Li aggiungo all'interno della pagina "Risorse Didattiche" nella sezione "Negozi Fisici Bitcoin"
