### ISSUE TITLE
Aggiunta Corso Bitcoin for Everyone 

### ISSUE THREAD

**Issue by gianlock** [ventunobtc/ventuno-space#35]
Potrebbe essere aggiunto il corso "Bitcoin for Everyone" della Saylor Academy, anche se in inglese.
Sono 12h di corso tenute da Stephen Leveira nel portale della Saylor Academy di Micheal Saylor.

Di seguito il link: https://learn.saylor.org/course/view.php?id=468

**Comment by waltermaffy** [comment]
Risorsa interessante ma purtroppo in inglese. Vorremmo cercare di mantenere il sito con risorse in italiano, altrimenti la lista potrebbe essere infinita

**Comment by gianlock** [comment]
Allora chiudo la issue.
Grazie.
